org.gradle.jvmargs=-Xmx3G
minecraft_version=26.1.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT
fabric_version=0.144.1+26.1
midnightlib_version = 1.9.2+26.1-fabric
archives_base_name=RTHuds-26.1.1
java_version=21
mod_version=5.1.1
maven_group=com.rtc

archive_minecraft_version=26.1
supported_version=26.1.1
modmenu_version=18.0.0-alpha.8